//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop_PhuocToan.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categories
    {
        public Categories()
        {
            this.Categories1 = new HashSet<Categories>();
            this.Products = new HashSet<Products>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Slug { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
    
        public virtual Staff Staff { get; set; }
        public virtual ICollection<Categories> Categories1 { get; set; }
        public virtual Categories Categories2 { get; set; }
        public virtual Staff Staff1 { get; set; }
        public virtual ICollection<Products> Products { get; set; }
    }
}
