//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop_PhuocToan.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public Staff()
        {
            this.Categories = new HashSet<Categories>();
            this.Categories1 = new HashSet<Categories>();
            this.ProductAttributes = new HashSet<ProductAttributes>();
            this.ProductAttributes1 = new HashSet<ProductAttributes>();
            this.ProductAttributes2 = new HashSet<ProductAttributes>();
            this.ProductImages = new HashSet<ProductImages>();
            this.ProductImages1 = new HashSet<ProductImages>();
            this.ProductImages2 = new HashSet<ProductImages>();
            this.Products = new HashSet<Products>();
            this.Products1 = new HashSet<Products>();
            this.Products2 = new HashSet<Products>();
        }
    
        public int Id { get; set; }
        public Nullable<int> StaffId { get; set; }
        public Nullable<System.Guid> GuidId { get; set; }
        public string Code { get; set; }
        public string UserName { get; set; }
        public string FullName { get; set; }
        public string UnitCode { get; set; }
        public string UnitName { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> Activated { get; set; }
        public string ActiveBy { get; set; }
        public int Type { get; set; }
        public string Password { get; set; }
        public string Avatar { get; set; }
        public string PermissionType { get; set; }
    
        public virtual ICollection<Categories> Categories { get; set; }
        public virtual ICollection<Categories> Categories1 { get; set; }
        public virtual ICollection<ProductAttributes> ProductAttributes { get; set; }
        public virtual ICollection<ProductAttributes> ProductAttributes1 { get; set; }
        public virtual ICollection<ProductAttributes> ProductAttributes2 { get; set; }
        public virtual ICollection<ProductImages> ProductImages { get; set; }
        public virtual ICollection<ProductImages> ProductImages1 { get; set; }
        public virtual ICollection<ProductImages> ProductImages2 { get; set; }
        public virtual ICollection<Products> Products { get; set; }
        public virtual ICollection<Products> Products1 { get; set; }
        public virtual ICollection<Products> Products2 { get; set; }
    }
}
